version: '3.8'
services:
    mysql:
        image: mysql:8
        container_name: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: geo_db
        ports:
        - "3306:3306"
        volumes:
            - mysql-data:/var/lib/mysql
            - ./mysql/init:/docker-entrypoint-initdb.d/
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "--host=localhost", "--user=root", "--password=root"]
            interval: 10s
            retries: 5
            start_period: 30s
            timeout: 10s

    backend:
        build: ./backend
        depends_on:
            mysql:
                condition: service_healthy
        command: sh -c "sleep 15 && java -jar app.jar"
        environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/geo_db
            SPRING_DATASOURCE_USERNAME: root
            SPRING_DATASOURCE_PASSWORD: root
        ports:
            - "8080:8080"

    frontend:
        build: ./frontend
        ports:
            - "3000:3000"
        depends_on:
            - backend


volumes:
    mysql-data: